---

- name: Destroy simpledemo
  connection: local
  gather_facts: no
  hosts: localhost

  vars_files:
    - vars/liveuser.yml

  roles:
  - down-simpledemo-project

  pre_tasks:
    - name: Verify Ansible Version
      assert:
        that:
          - "ansible_version.major == 2"
          - "ansible_version.minor >= 4"
        msg: "This script is only supported with the 2.4 version of Ansible"
