---

- name: Set test cluster
  shell: "oc login {{ test_cluster_public_hostname }}:{{ test_cluster_port }} -u {{ test_cluster_username }} -p {{ test_cluster_password }}"

- name: Create the test project
  shell: "oc new-project simpledemo-app-test --display-name='Catalog Test'"

- name: Deploy the application into the test environment
  shell: "oc process -f https://raw.githubusercontent.com/ecwpz91/openshift-c2c-demo/master/templates/simpledemo-template.yml | oc apply -f -"

- name: Create a Jenkins service account that the CI/CD on the development cluster will use
  shell: "oc create sa jenkins"

- name: Give the Jenkins SA permissions to work with the project
  shell: "oc policy add-role-to-user edit system:serviceaccount:simpledemo-app-test:jenkins -n simpledemo-app-test"

- name: Get the token for the Jenkins service account
  shell: "oc sa get-token jenkins"

- name: Disable the triggers for the application since we want the pipeline to control the deployment
  shell: "oc set triggers dc simpledemo-app --containers='simpledemo-app' --from-image='simpledemo-app:latest' --manual=true -n simpledemo-app-test"

- name: Logout of cluster
  shell: "oc logout"
