---

- name: Set dev cluster
  shell: "oc login {{ dev_cluster_public_hostname }}:{{ dev_cluster_port }} -u {{ dev_cluster_username }} -p {{ dev_cluster_password }}"

- name: Create a CI/CD project
  shell: oc new-project simpledemo-cicd --display-name='Simple Demo CI/CD'

- name: Create the jenkins-image-management image
  shell: oc process -f https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/master/jenkins-slaves/templates/jenkins-slave-image-mgmt-template.yml | oc apply -f-

- name: Create a new persistent jenkins application.
  shell: oc new-app --template=jenkins-persistent

- name: Deploy the pipeline to the project
  shell: "oc create -f https://raw.githubusercontent.com/ecwpz91/openshift-c2c-demo/master/templates/cross-cluster-pipeline.yml"

- name: Configure the pipeline variables by editing the pipeline variables, notably update the TEST_REGISTRY which is the registry address for the test cluster
  shell: "oc sa get-token jenkins"

- name: Set cluster admin
  shell: "oc login {{ dev_cluster_public_hostname }}:{{ dev_cluster_port }} -u {{ openshift_cluster_admin_username }} -p {{ openshift_cluster_admin_password }}"

- name: Create the openshift template persistent
  shell: "oc create -f https://raw.githubusercontent.com/ecwpz91/openshift-c2c-demo/master/templates/simpledemo-template.yml -n openshift"

- name: Set dev cluster
  shell: "oc login {{ dev_cluster_public_hostname }}:{{ dev_cluster_port }} -u {{ dev_cluster_username }} -p {{ dev_cluster_password }}"

- name: Create the development project
  shell: "oc new-project simpledemo-dev --display-name='Simple Demo Devel'"

- name: Create the application in the Development using the template
  shell: "oc process -f https://raw.githubusercontent.com/ecwpz91/openshift-c2c-demo/master/templates/simpledemo-template.yml | oc apply -f -"

- name: Disable the triggers for the application since we want the pipeline to control the deployment
  shell: "oc set triggers dc simpledemo --containers='simpledemo' --from-image='simpledemo:latest' --manual=true -n simpledemo-dev"

- name: Add permisions for the jenkins service account to work with the development project
  shell: "oc policy add-role-to-user edit system:serviceaccount:simpledemo-cicd:jenkins -n simpledemo-dev"

- name: Logout of cluster
  shell: "oc logout"
