# add_operator_user/tasks/main.yml
---

- name: Create operator user
  uri:
    url: "https://{{ management_route }}/api/users"
    body_format: json
    method: POST
    user: "{{ management_admin_username | default('admin') }}"
    password: "{{ management_admin_password | default('smartvm') }}"
    validate_certs: no
    # Docs on formatting the BODY of the POST request:
    # http://manageiq.org/docs/reference/latest/api/reference/users#creating-users
    body:
      userid: "{{ management_username | default('devops')}}"
      password: "{{ management_password | default('smartvm')}}"
      name: "Operator"
      group: { "id" : "3" }
