---

- name: Ensure this cluster is a container provider
  uri:
    url: "https://{{ management_route }}/api/providers"
    body_format: json
    method: POST
    user: "{{ management_admin_username | default('admin') }}"
    password: "{{ management_admin_password | default('smartvm') }}"
    validate_certs: no
    # Docs on formatting the BODY of the POST request:
    # http://manageiq.org/docs/reference/latest/api/reference/providers.html#specifying-connection-configurations
    body:
      connection_configurations:
        - authentication: {auth_key: "{{ management_bearer_token }}", authtype: bearer, type: AuthToken}
          endpoint: {role: default, security_protocol: ssl-without-validation, verify_ssl: 0}
      hostname: "{{ openshift_master_cluster_public_hostname }}"
      name: "{{ openshift_master_cluster_public_hostname | default(None) }}"
      port: "{{ openshift_master_api_port | default('8443') }}"
      type: "ManageIQ::Providers::Openshift::ContainerManager"
